Develop
Valleycate/java-filmorate pull request #23
Opened 2023-08-06 09:49 UTC by Christina1407

2023-08-07 10:51 UTC, AnastasiyaFomkina requested changes
Нужно добавить описание того, какие задачи выполнила группа, в описании пул-реквеста или в файле `readme`

2023-08-07 10:51 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    public ReviewService(ReviewDbStorage reviewStorage, UserService userService, FilmService filmService, UserStorage userStorage, UserService userService1, FilmStorage filmStorage, ReviewLikeDbStora
Половина параметров конструктора лишняя, нужно избавиться от дублирующихся сервисов

2023-08-07 10:51 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +                Optional.ofNullable(reviewLikeStorage.sumLikeDislike(review.getReviewId())).orElse(0)));
Вместо дубдирования кода нужно использовать метод `enrichReviewsByUseful` с 54 строки

2023-08-07 10:51 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    private void enrichReviewsByUseful(Review review) {
Лучше переименовать в `enrichReviewByUseful`, чтобы не путать с методом выше

2023-08-07 10:51 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        feedStorage.save(Feed.builder()
Создание объекта Feed нужно вынести в отдельный метод внутри отдельного утильного класса и сдедать его публичным, чтобы можно было переиспользовать по всему коду. 
После нужно заменить по всему коду создание `Feed` через новый метод.

2023-08-07 10:51 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +            if (!whoLikeReview.contains(userId) && !whoDislikeReview.contains(userId)) { //проверяем, что от этого юзера нет лайка или дизлайка
Условие повторяется на 160 строке, нужно его вынести в отдельный метод и переиспользовать

2023-08-07 10:51 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +                deleteLikeDislike(reviewId, userId, false); //удаляем дизлайк
Код со строк 153-156  и 164-167 отличается только параметром метода `deleteLikeDislike` и параметром строки в логировании, нужно его вынести в отдельны метод с параметрами `boolean isLike, String nameOfDelete, String nameOfAdd`

2023-08-07 10:51 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +                log.info("Пользователь id = : " + userId + " поставил like отзыву id = " + reviewId);
При логировании параметров, лучше использовать заполнитель(placeholder) {}, а не конкатенацию.
Тогда код будет выглядеть более лаконично
```suggestion
                log.info("Пользователь id: {} поставил like отзыву id: {}", userId, reviewId);
```
Поправь, пожалуйста, все логирование в классе подобным образом

2023-08-07 10:51 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private static void checkNameUser(User user) {
Используется только внутри данного класса, модификатор `static` лишний

2023-08-07 10:51 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/FeedDbStorage.java
> +        KeyHolder keyHolder = new GeneratedKeyHolder();
Не используется, строчку нужно удалить

2023-08-07 10:51 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/FilmDbStorage.java
> +            Film obj = new Film();
Код со строк 268-276 повторяется на строках 290-298, нужно выделить их в отдельный метод и переиспользовать, чтобы избавиться от дублирований

2023-08-07 10:51 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/FilmDirectorsDbStorage.java
> +    public ArrayList<Director> getDirectorsOfFilm(int filmId) {
```suggestion
    public List<Director> getDirectorsOfFilm(int filmId) {
```

2023-08-07 10:51 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/GenreDbStorage.java
>      protected ArrayList<GenreModel> updateGenre(ArrayList<GenreModel> genreFilm, int filmId) {
```suggestion
    protected List<GenreModel> updateGenre(ArrayList<GenreModel> genreFilm, int filmId) {
```

2023-08-07 10:51 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/GenreDbStorage.java
>      protected ArrayList<GenreModel> getGenresFilm(int filmId) {
```suggestion
    protected List<GenreModel> getGenresFilm(int filmId) {
```

2023-08-07 10:51 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/ReviewDbStorage.java
> +        KeyHolder keyHolder = new GeneratedKeyHolder();
Не используется. Нужно удалить

2023-08-07 10:51 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/ReviewLikeDbStorage.java
> +    public void deleteLikeDislike(Long reviewId, int userId, boolean isLike) {
Параметр `isLike` не используется

2023-08-07 10:51 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/ReviewLikeDbStorage.java
> +        KeyHolder keyHolder = new GeneratedKeyHolder();
Не используется

2023-08-07 10:51 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/ReviewLikeDbStorage.java
> +        KeyHolder keyHolder = new GeneratedKeyHolder();
Не используется

2023-08-07 10:51 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/ReviewLikeDbStorage.java
> +        KeyHolder keyHolder = new GeneratedKeyHolder();
Не используется

2023-08-07 10:51 UTC, AnastasiyaFomkina commented on src/test/java/FilmControllerTest.java
Тесты удалять не нужно, верните, пожалуйста

2023-08-07 10:51 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/DirectorRowMapper.java
Лучше разбить папку DAO по подпакетам, например, на мапперы, хранилища и интерфейсы

2023-08-07 10:51 UTC, AnastasiyaFomkina requested changes
Нужно добавить описание того, какие задачи выполнила группа, в описании пул-реквеста или в файле `readme`

2023-08-07 21:10 UTC, AnastasiyaFomkina requested changes

2023-08-07 21:10 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/util/FeedSaver.java
> +    public static void saveFeed(Integer userId, Long entityId, EnumEventType eventType, EnumOperation operation) {
В данном случае не должен быть static, объект класса `FeedSaver` стоит внедрять в сервисы с помощью dependency injection и использовать в коде, как любой другой компонент спинга

2023-08-07 21:10 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/util/FeedSaver.java
> +    private static FeedDbStorage feedStorage;
Должен быть final, но не static

2023-08-07 21:10 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/util/FeedSaver.java
> +    private FeedSaver(FeedDbStorage feedStorage) {
Можно заменить на `@RequiredArgsConstructor`

2023-08-08 23:48 UTC, AnastasiyaFomkina approved these changes

2023-08-08 23:54 UTC, AnastasiyaFomkina reviewed
Вы проделали большую работу! У вас получился отличный проект и появились навыки работы в команде. Здорово, что выбрали усложнённую версию и добавили режиссера и поиск. Вы хорошо разобрались во взаимодействие между слоями сервис - контроллер - репозиторий и у вас получились клевые запросы к таблицам. Так держать 🔥

2023-08-08 23:54 UTC, AnastasiyaFomkina approved these changes

2023-08-09 07:11 UTC, Valleycate approved these changes

2023-08-09 07:11 UTC, merged